### ISSUE TITLE
Illegal access getting default policy

### ISSUE THREAD

**Issue by Thihup** [omnifaces/exousia#2]
Running Exousia with JDK 16 (or JDK 15 with --illegal-access=deny) leads to following exception:
```
java.lang.IllegalAccessException: class org.omnifaces.exousia.modules.def.DefaultPolicy cannot access class sun.security.provider.PolicyFile (in module java.base) because module java.base does not export sun.security.provider to unnamed module @3ee0b4f7
```

Is there a replacement for this unsupported API? Otherwise, we'll need to add `--add-exports=java.base/sun.security.provider=ALL-UNNAMED` for this to work

**Comment by arjantijms** [comment]
The illegal class is returned by `Security.getProperty("policy.provider")`. I think just using `Policy.getPolicy()` before the new one is installed should do the trick.

**Comment by Thihup** [comment]
@arjantijms Do you think it is possible to release a new version before the release of the JDK 16?

**Comment by arjantijms** [comment]
@Thihup yes, I'll look into this soon. I fixed an identical issue in GlassFish already.

**Comment by arjantijms** [comment]
Exousia 1.1 with fix released: https://repo1.maven.org/maven2/org/omnifaces/exousia/1.1/

Thanks for the report! :)
